"""
review_service/output/adr_writer.py — Write an ADR when architectural risks are found.

ADR is written only when architect_findings contains [CRITICAL] or [HIGH]
entries in the architecture_risks section.

Output path: docs/03-DECISIONS/ADR-YYYY-MM-DD-HHMM-architect-review.md
Naming is timestamp-based (not sequential) to avoid numbering conflicts.
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from ..state import ReviewState

_ADR_DIR = Path("F:/Projects/sage_kaizen_ai/docs/03-DECISIONS")


def write_adr_if_needed(state: ReviewState) -> str | None:
    """
    Write an ADR if the findings contain CRITICAL or HIGH architectural risks.
    Returns the file path on write, or None if no ADR was warranted.
    """
    findings = state.get("architect_findings", "") + state.get("synthesis", "")
    if not _has_architectural_risk(findings):
        return None

    _ADR_DIR.mkdir(parents=True, exist_ok=True)

    now       = datetime.now()
    datestamp = now.strftime("%Y-%m-%d-%H%M")
    filename  = f"ADR-{datestamp}-architect-review.md"
    path      = _ADR_DIR / filename

    content   = _build_adr(state, now)
    path.write_text(content, encoding="utf-8")
    return str(path)


def _has_architectural_risk(text: str) -> bool:
    """Return True if the text contains CRITICAL or HIGH architectural risk findings."""
    # Look for CRITICAL/HIGH severity tags near architecture-related keywords
    critical_or_high = re.search(r"\[(?:CRITICAL|HIGH)\]", text)
    arch_keywords    = re.search(
        r"architecture_risk|architectural|module boundary|tight coupling|layering|service contract",
        text, re.IGNORECASE,
    )
    return bool(critical_or_high and arch_keywords)


def _build_adr(state: ReviewState, now: datetime) -> str:
    mode      = state.get("mode", "unknown")
    timestamp = now.strftime("%Y-%m-%d %H:%M")
    synthesis_excerpt = (state.get("synthesis") or "")[:3000]

    # Extract architecture_risks section from architect_findings if present
    findings   = state.get("architect_findings", "")
    risks_section = _extract_section(findings, "architecture_risks") or synthesis_excerpt[:1500]

    return f"""\
# ADR — Architect Review Findings: {timestamp}

## Status
Proposed

---

## Context

This ADR was automatically generated by the Sage Kaizen Architect Review Service
during a `{mode}` mode review on {timestamp}.

It records architectural risks identified by the ARCHITECT brain (Qwen3.5-27B-Q6_K)
that require a documented decision or explicit acceptance.

### Changed Files
{chr(10).join(f"- {f}" for f in state.get("changed_files", [])[:20])}

---

## Architecture Risks Identified

{risks_section}

---

## Decision

> **TODO**: Fill in the architectural decision after reviewing the findings above.

Options considered:
- Accept the risk (document rationale)
- Refactor to address the risk
- Defer to a specific milestone

---

## Consequences

### Positive
- (fill in)

### Negative
- (fill in)

### Risks
- (fill in)

### Follow-up Actions
- [ ] Review findings in [reviews/](../../../reviews/) for full synthesis
- [ ] Assign owner and target date for each CRITICAL/HIGH item

---

## Alignment

Does this decision:
- Respect dual-brain pattern? (fill in)
- Preserve invariants? (fill in)
- Maintain observability? (fill in)
- Avoid architectural coupling? (fill in)

---

*Generated by Sage Kaizen Architect Review Service | Review mode: {mode}*
"""


def _extract_section(text: str, section_name: str) -> str:
    """Extract the content of a named section from architect findings."""
    pattern = rf"##\s+{re.escape(section_name)}(.*?)(?=\n##\s|\Z)"
    m = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
    if m:
        return m.group(1).strip()[:2000]
    return ""
