"""
review_service/output/review_writer.py — Write the main review markdown file.

Output path: reviews/YYYY-MM-DD-HHMM-{mode}-review.md
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from ..state import ReviewState

_REVIEWS_DIR = Path("F:/Projects/sage_kaizen_ai/reviews")


def write_review_file(state: ReviewState) -> str:
    """Write the synthesis to reviews/YYYY-MM-DD-HHMM-{mode}-review.md and return the path."""
    _REVIEWS_DIR.mkdir(parents=True, exist_ok=True)

    now      = datetime.now()
    datestamp = now.strftime("%Y-%m-%d-%H%M")
    mode     = state.get("mode", "unknown")
    filename = f"{datestamp}-{mode}-review.md"
    path     = _REVIEWS_DIR / filename

    header = _build_header(state, now)
    content = header + "\n\n" + (state.get("synthesis") or "_No synthesis generated._")

    path.write_text(content, encoding="utf-8")
    return str(path)


def _build_header(state: ReviewState, now: datetime) -> str:
    mode           = state.get("mode", "unknown")
    changed        = state.get("changed_files", [])
    overflow       = state.get("overflow_files", [])
    scope_chars    = state.get("scope_char_count", 0)
    # Extract thread_id from mode for display (runner sets it externally)
    timestamp      = now.strftime("%Y-%m-%d %H:%M")

    overflow_note  = f"\n- **Overflow files (not reviewed)**: {len(overflow)}" if overflow else ""

    return (
        f"# Sage Kaizen Architect Review\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| **Date** | {timestamp} |\n"
        f"| **Mode** | {mode} |\n"
        f"| **ARCHITECT model** | Qwen3.5-27B-Q6\\_K (port 8012, CUDA0) |\n"
        f"| **Changed files** | {len(changed)} |\n"
        f"| **Scope chars** | {scope_chars:,} |\n"
        f"\n"
        f"> This review was generated by the Sage Kaizen Architect Review Service.\n"
        f"> No changes were applied automatically. All suggestions require manual review.\n"
        f"{overflow_note}"
    )
